INSERT INTO public."ai-knowledge-base-table" (title, body)
VALUES (
        'Understanding React Server Components',
        'React Server Components represent a fundamental shift in how we think about rendering in React applications. Unlike traditional React components that run in the browser, Server Components execute exclusively on the server and never ship their JavaScript to the client. This means you can directly access databases, file systems, and other server-side resources without exposing sensitive logic to the browser. Server Components are ideal for data fetching because they eliminate the need for useEffect hooks and loading states for initial data. The component renders on the server with the data already available, and the resulting HTML is sent to the browser. This approach significantly reduces the JavaScript bundle size since the component code itself never reaches the client.'
    ),
    (
        'Next.js App Router Architecture',
        'The App Router introduced in Next.js 13 represents a complete rethinking of how routing works in Next.js applications. Unlike the Pages Router where every file in the pages directory becomes a route, the App Router uses a folder-based convention where only files named page.tsx are treated as routes. This allows colocating components, utilities, and tests alongside the routes they belong to. The App Router enables nested layouts through layout.tsx files, which persist across navigation without remounting. Loading states, error boundaries, and not-found pages are all handled through special file conventions. The most significant change is that all components are Server Components by default, requiring explicit opt-in to client-side rendering through the use client directive.'
    ),
    (
        'Supabase Row Level Security',
        'Row Level Security is a PostgreSQL feature that Supabase uses to control data access at the database level. When RLS is enabled on a table, all operations are blocked by default until you explicitly create policies that allow them. Policies are SQL expressions that evaluate to true or false for each row and each operation. A common pattern is to restrict users to only their own data using auth.uid() which returns the ID of the authenticated user. RLS is more secure than application-level authorization because it enforces rules in the database itself, meaning even a bug in your application code cannot bypass the access controls. During development without authentication, you can create an open policy that allows all operations, which you then replace with proper user-scoped policies when auth is added.'
    ),
    (
        'TypeScript Strict Mode Benefits',
        'Enabling strict mode in your TypeScript configuration activates a collection of type checking rules that catch common bugs at compile time. The most impactful rules include strictNullChecks which prevents you from assigning null or undefined to variables that do not explicitly allow it, noImplicitAny which requires explicit type annotations when TypeScript cannot infer the type, and strictFunctionTypes which ensures function parameter types are checked correctly. Without strict mode, TypeScript is considerably more permissive and allows patterns that frequently cause runtime errors. The initial overhead of fixing all the errors when enabling strict mode is worth it because it eliminates an entire category of bugs. Every professional TypeScript codebase should have strict mode enabled from the start.'
    ),
    (
        'pgvector and Semantic Search',
        'pgvector is a PostgreSQL extension that adds support for storing and querying vector embeddings directly in your database. Vector embeddings are numerical representations of text where semantically similar content is represented by vectors that are close together in high-dimensional space. This enables semantic search, where queries find results based on meaning rather than exact keyword matches. For example, searching for productivity would also surface results about focus, time management, and efficiency even if those exact words are not in the query. To implement semantic search, you generate embeddings for your content using a model like text-embedding-ada-002 from OpenAI, store them in a vector column, and then query using cosine similarity or dot product distance. Supabase supports pgvector natively, making it straightforward to add semantic search to any Supabase project.'
    ),
    (
        'Vercel AI SDK for Streaming UIs',
        'The Vercel AI SDK is a TypeScript library designed specifically for building AI-powered user interfaces in Next.js and other React frameworks. Its most powerful feature is built-in support for streaming responses from language models, which allows users to see the AI response appear word by word rather than waiting for the entire response to generate. The SDK provides the useChat hook for managing conversation state on the client side, handling message history, loading states, and error handling automatically. On the server side, the streamText function connects to any supported LLM provider including OpenAI and Anthropic and handles the streaming protocol. The SDK also supports tool calling, which allows the AI to invoke functions in your application to fetch data or perform actions based on the conversation.'
    ),
    (
        'Repository Pattern in Next.js',
        'The repository pattern is an architectural approach that creates an abstraction layer between your application logic and your data source. In a Next.js application, this means creating dedicated files that contain all database queries, while pages, Server Actions, and components interact with the database only through this layer. The primary benefit is that swapping databases or ORMs requires changes only to the repository files, leaving the rest of the application completely untouched. It also makes testing easier because you can mock the repository layer without needing a real database connection. In this project the repository lives in lib/db/notes.repository.ts and all Supabase queries are written there. Server Actions call the repository, and pages call either the repository directly for reads or Server Actions for mutations.'
    ),
    (
        'Server Actions and Data Mutations',
        'Server Actions are asynchronous functions marked with the use server directive that run on the server but can be called directly from Client Components as if they were regular functions. They solve a specific problem in App Router: Client Components cannot import server-only modules like the Supabase client or cookies, but they need a way to trigger server-side mutations like creating or deleting records. Before Server Actions, this required creating API route handlers and using fetch to call them. Server Actions eliminate this boilerplate and provide a more direct programming model. They also integrate with React transitions for optimistic updates and work with the native HTML form action attribute for progressive enhancement. The recommended pattern is to keep Server Actions thin, delegating actual business logic and database operations to a separate service or repository layer.'
    ),
    (
        'Web Core Vitals Explained',
        'Core Web Vitals are a set of metrics defined by Google that measure the user experience of a web page. Largest Contentful Paint measures loading performance and specifically tracks when the largest image or text block becomes visible in the viewport. A good LCP score is under 2.5 seconds. Cumulative Layout Shift measures visual stability by tracking how much page elements move unexpectedly during loading. A good CLS score is under 0.1. Interaction to Next Paint replaced First Input Delay in 2024 and measures the responsiveness of the page to user interactions by tracking the time from when a user interacts to when the browser renders the next frame. INP should be under 200 milliseconds. These metrics directly influence Google search rankings making them important for SEO as well as user experience.'
    ),
    (
        'useEffect Patterns and Pitfalls',
        'useEffect is one of the most misused hooks in React. The most common mistake is using it to fetch data on component mount, which creates a waterfall of requests and leads to race conditions. In App Router, data fetching should happen in Server Components using async await, eliminating the need for useEffect for data fetching entirely. When useEffect is genuinely needed, the dependency array must accurately reflect all values the effect depends on. Missing dependencies cause stale closures where the effect reads outdated values. The cleanup function is critical for effects that set up subscriptions, timers, or event listeners. Without cleanup, these continue running after the component unmounts and cause memory leaks. A useful mental model is to think of useEffect as a synchronization mechanism for keeping non-React systems in sync with React state, rather than a lifecycle hook.'
    ),
    (
        'JavaScript Event Loop Deep Dive',
        'The JavaScript event loop is the mechanism that allows JavaScript to be non-blocking despite running on a single thread. The call stack executes synchronous code one frame at a time. When asynchronous operations like setTimeout or fetch complete, their callbacks are placed in the callback queue. The event loop checks if the call stack is empty and if so, moves the next item from the callback queue onto the stack. Promises use a separate microtask queue which has higher priority than the callback queue. This means all resolved promise callbacks execute before any setTimeout callbacks, even a setTimeout with zero delay. Understanding this explains why awaiting a promise in a loop can cause performance issues and why requestAnimationFrame is more reliable than setTimeout for animation timing.'
    ),
    (
        'Git Branching Strategy',
        'A consistent branching strategy is essential for collaborative development and clean version history. The trunk-based development approach uses short-lived feature branches that are merged frequently into the main branch, reducing merge conflicts and integration issues. Each branch should represent a single feature or fix, named descriptively like feature/add-semantic-search or fix/note-detail-crash. Commit messages should follow a consistent format with a type prefix such as feat, fix, refactor, or chore followed by a short description of what changed and why. Before opening a pull request, rebase onto the latest main to resolve conflicts locally and keep the git history linear. Small focused pull requests are easier to review, easier to revert if they cause issues, and less likely to introduce bugs than large changes.'
    ),
    (
        'CSS Layout with Flexbox and Grid',
        'Flexbox and CSS Grid solve different layout problems and are most powerful when used together. Flexbox is a one-dimensional layout system that distributes items along a single axis, either horizontally or vertically. It excels at aligning items within a component, distributing space between navigation items, or centering content. Grid is a two-dimensional system that handles rows and columns simultaneously. It is the right choice for overall page layout, card grids, and any design that requires alignment across both axes. A common pattern is to use Grid for the macro layout of the page and Flexbox for the micro layout of individual components. In Tailwind CSS, flex and grid utilities map directly to these properties, with gap replacing both column-gap and row-gap for consistent spacing in both systems.'
    ),
    (
        'Authentication Patterns in Next.js',
        'Authentication in Next.js App Router involves coordinating between server-side session management and client-side state. The most robust approach stores the session in an HTTP-only cookie that cannot be accessed by JavaScript, preventing XSS attacks from stealing tokens. Middleware runs before every request and can check the session cookie to redirect unauthenticated users before the page even renders. Server Components can read the session to personalize content or gate access to data. Client Components can access a lightweight session object for UI purposes like displaying the user name. Supabase Auth handles all of this and integrates with the ssr package to correctly manage cookies in Next.js. The auth flow for this project would involve protecting the notes routes in middleware and scoping all database queries to the authenticated user through RLS policies.'
    ),
    (
        'Database Query Optimization',
        'Inefficient database queries are one of the most common causes of slow web applications. The most impactful optimization is selecting only the columns you need rather than using SELECT star, which reduces the amount of data transferred from the database. Indexes dramatically speed up queries that filter or sort by specific columns, but they come with a write overhead since the index must be updated on every insert and update. The N plus one problem occurs when fetching a list of records and then making a separate query for each record to fetch related data. This should be replaced with a single JOIN query or a batch query. Query execution plans, available through EXPLAIN ANALYZE in PostgreSQL, show exactly how the database is executing a query and where the bottlenecks are. Supabase exposes this through the SQL editor.'
    ),
    (
        'TypeScript Utility Types',
        'TypeScript ships with a set of built-in utility types that transform existing types into new ones. Pick creates a new type containing only the specified properties from a type, useful for create operations where you do not want to include auto-generated fields like id and created_at. Omit is the inverse, creating a type with specific properties removed. Partial makes all properties optional, useful for update operations where you only want to change some fields. Required makes all properties mandatory. Record creates an object type with specified keys and value types. NonNullable removes null and undefined from a type. These utilities eliminate the need to manually duplicate type definitions and keep related types in sync automatically when the source type changes.'
    ),
    (
        'Error Handling in Next.js',
        'Robust error handling in Next.js App Router involves multiple layers. The error.tsx file convention creates an error boundary for a route segment that catches rendering errors and displays a fallback UI with a retry button. The not-found.tsx convention renders when notFound() is called, providing a custom 404 page. For data fetching errors in Server Components, try catch blocks prevent the entire page from crashing when a database query fails. In Server Actions, errors should be caught and returned as structured error objects rather than thrown, since thrown errors in Server Actions produce generic error messages in production. Client Components should handle fetch errors gracefully with appropriate user feedback. A global error.tsx in the app directory catches errors that escape all other boundaries.'
    ),
    (
        'Accessibility in Web Applications',
        'Web accessibility ensures your application is usable by people with disabilities and is measured against the Web Content Accessibility Guidelines. Semantic HTML is the foundation, using elements like nav, main, article, and button for their intended purposes rather than styling divs to look like interactive elements. All interactive elements must be keyboard accessible and focusable. Images require meaningful alt text that describes the content for screen reader users. Color alone should never convey information since colorblind users will miss it. Form inputs need associated labels either through the for attribute or by wrapping the input in the label element. ARIA attributes should be used only when native HTML semantics are insufficient. Automated tools like axe can catch around 30 percent of accessibility issues, but manual keyboard testing and screen reader testing are essential for full coverage.'
    ),
    (
        'Environment Variables in Next.js',
        'Next.js has a specific convention for environment variables that controls whether they are available on the server, the client, or both. Variables prefixed with NEXT_PUBLIC are bundled into the client-side JavaScript and are accessible in both Server and Client Components. Variables without this prefix are only available on the server and are never sent to the browser. This distinction is critical for security. Database connection strings, API secret keys, and service role tokens must never have the NEXT_PUBLIC prefix. The public Supabase anon key and URL can have the prefix because they are designed to be used in the browser with RLS policies providing the security layer. Environment variables are loaded from .env.local for local development. In production on Vercel, they are configured through the project settings dashboard.'
    ),
    (
        'Performance Optimization Strategies',
        'Frontend performance optimization starts with measuring before making changes. Lighthouse in Chrome DevTools provides a comprehensive audit covering performance, accessibility, SEO, and best practices. The performance score is heavily influenced by the Core Web Vitals metrics. The highest impact optimizations are usually image optimization, eliminating render-blocking resources, and reducing JavaScript bundle size. In Next.js, the Image component handles image optimization automatically. Bundle analysis using next bundle-analyzer reveals which dependencies contribute most to bundle size, often exposing large libraries that can be replaced with smaller alternatives or loaded lazily. Code splitting with dynamic imports delays loading non-critical components until they are needed. Server Components are the most impactful architectural change for performance because they move code off the client entirely, reducing the amount of JavaScript the browser needs to download, parse, and execute.'
    );