drop extension if exists "pg_net";

create extension if not exists "vector" with schema "public";


  create table "public"."ai-knowledge-base-table" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text default ''::text,
    "body" text,
    "embedding" public.vector(1536)
      );


alter table "public"."ai-knowledge-base-table" enable row level security;

CREATE INDEX "ai-knowledge-base-table_embedding_idx" ON public."ai-knowledge-base-table" USING ivfflat (embedding public.vector_cosine_ops);

CREATE UNIQUE INDEX "ai-knowledge-base-table_pkey" ON public."ai-knowledge-base-table" USING btree (id);

alter table "public"."ai-knowledge-base-table" add constraint "ai-knowledge-base-table_pkey" PRIMARY KEY using index "ai-knowledge-base-table_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.match_notes(query_embedding public.vector, match_count integer DEFAULT 5, match_threshold double precision DEFAULT 0.3)
 RETURNS TABLE(id bigint, title text, body text, created_at timestamp with time zone, similarity double precision)
 LANGUAGE sql
 STABLE
AS $function$
  select
    id,
    title,
    body,
    created_at,
    1 - (embedding <=> query_embedding) as similarity
  from "ai-knowledge-base-table"
  where embedding is not null
    and 1 - (embedding <=> query_embedding) > match_threshold
  order by embedding <=> query_embedding
  limit match_count;
$function$
;

CREATE OR REPLACE FUNCTION public.search_notes(search_query text)
 RETURNS SETOF public."ai-knowledge-base-table"
 LANGUAGE sql
 STABLE
AS $function$
  select * from "ai-knowledge-base-table"
  where title ilike '%' || search_query || '%'
     or body ilike '%' || search_query || '%';
$function$
;

grant delete on table "public"."ai-knowledge-base-table" to "anon";

grant insert on table "public"."ai-knowledge-base-table" to "anon";

grant references on table "public"."ai-knowledge-base-table" to "anon";

grant select on table "public"."ai-knowledge-base-table" to "anon";

grant trigger on table "public"."ai-knowledge-base-table" to "anon";

grant truncate on table "public"."ai-knowledge-base-table" to "anon";

grant update on table "public"."ai-knowledge-base-table" to "anon";

grant delete on table "public"."ai-knowledge-base-table" to "authenticated";

grant insert on table "public"."ai-knowledge-base-table" to "authenticated";

grant references on table "public"."ai-knowledge-base-table" to "authenticated";

grant select on table "public"."ai-knowledge-base-table" to "authenticated";

grant trigger on table "public"."ai-knowledge-base-table" to "authenticated";

grant truncate on table "public"."ai-knowledge-base-table" to "authenticated";

grant update on table "public"."ai-knowledge-base-table" to "authenticated";

grant delete on table "public"."ai-knowledge-base-table" to "service_role";

grant insert on table "public"."ai-knowledge-base-table" to "service_role";

grant references on table "public"."ai-knowledge-base-table" to "service_role";

grant select on table "public"."ai-knowledge-base-table" to "service_role";

grant trigger on table "public"."ai-knowledge-base-table" to "service_role";

grant truncate on table "public"."ai-knowledge-base-table" to "service_role";

grant update on table "public"."ai-knowledge-base-table" to "service_role";


  create policy "allow all operations - dev only"
  on "public"."ai-knowledge-base-table"
  as permissive
  for all
  to public
using (true)
with check (true);



  create policy "public can read instruments"
  on "public"."ai-knowledge-base-table"
  as permissive
  for select
  to anon
using (true);



